/**
 * Boot integrity check (CLAUDE.md §5.3).
 *
 * A corrupt SQLite file is not hypothetical on desktop — power loss, a killed
 * process mid-checkpoint, or cloud-sync software rewriting the file underneath
 * the app all produce it. Detecting it at boot and quarantining the file lets
 * the user keep working with a fresh database instead of hitting an unexplained
 * crash on every launch.
 */
import Database from 'better-sqlite3'
import { existsSync, renameSync } from 'node:fs'

export type IntegrityStatus = 'ok' | 'missing' | 'corrupt'

export interface IntegrityReport {
  status: IntegrityStatus
  detail?: string
  quarantinedTo?: string
}

export function checkIntegrity(dbPath: string): IntegrityReport {
  if (!existsSync(dbPath)) return { status: 'missing' }

  let db: Database.Database | undefined
  try {
    db = new Database(dbPath, { readonly: true })
    // quick_check is dramatically faster than integrity_check on large files
    // and catches the structural corruption that actually matters at boot.
    const rows = db.pragma('quick_check') as Array<{ quick_check: string }>
    const first = rows[0]?.quick_check
    return first === 'ok'
      ? { status: 'ok' }
      : { status: 'corrupt', detail: rows.map((r) => r.quick_check).join('; ') }
  } catch (err) {
    return { status: 'corrupt', detail: err instanceof Error ? err.message : String(err) }
  } finally {
    db?.close()
  }
}

/**
 * Move a corrupt database aside so the app can start with a fresh one. The file
 * is renamed rather than deleted — it may still be recoverable, and silently
 * destroying a user's data is never the right default.
 */
export function quarantine(dbPath: string): string {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-')
  const target = `${dbPath}.corrupt-${stamp}`
  renameSync(dbPath, target)
  for (const suffix of ['-wal', '-shm']) {
    if (existsSync(dbPath + suffix)) {
      try {
        renameSync(dbPath + suffix, target + suffix)
      } catch (err) {
        // The sidecar files are regenerated by SQLite; failing to move one is
        // not worth aborting a recovery over, but it should be visible.
        console.warn(`quarantine: could not move ${suffix} file: ${String(err)}`)
      }
    }
  }
  return target
}
